spring:
  profiles:
    active: db, core, wx
  message:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.sandwich.litemall.wx:  DEBUG
    org.sandwich.litemall:  ERROR